name: portfolio
description: A portfolio build by using flutter for web.
# version: 1.0.0
#homepage: http://zubair-portfolio.surge.sh/#/
#author: zubairehman <zubairehman.work@gmail.com>

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies: 

dev_dependencies:
  # Enables the `pub run build_runner` command
  build_runner: ^2.4.6

  # Includes the JavaScript compilers
  build_web_compilers: ^4.0.5

  # The Font Awesome Icon pack available as Flutter Icons.
  font_awesome_flutter: ^10.5.0

#  font_awesome_flutter: ^8.5.0

# flutter_web packages are not published to pub.dartlang.org
# These overrides tell the package tools to get them from GitHub

flutter:
  uses-material-design: true
